### ISSUE TITLE
how to add an option?

### ISSUE THREAD

**Issue by Joppla** [iatkin/leaflet-svgicon#2]
Thanks for developing this tool!

Maybe not an issue, but I'm terrible wrestling with adding an option to the icon.

In the [README.md](https://github.com/iatkin/leaflet-svgicon/blob/master/README.md) is add the example to add an icon to a map:
`var marker = new L.Marker(latlng, { icon: new L.DivIcon.SVGIcon() })`

But how can I add the option **_circleText_** to this code?

I made the following code, but the text "**_hello_**" is not at the marker.
```
var myIcon = new L.DivIcon.SVGIcon({circleText: 'hello'});
var marker = new L.Marker.SVGMarker([51.5, -0.09], { icon: myIcon}).addTo(mymap);
```
Please add an example in the README

**Comment by iatkin** [comment]
Your issue is that you can't directly pass a custom icon to SVGMarker. To customize the icon, pass a dictionary under the option "iconOptions". For your example, the intended use is 
```
var marker = new L.Marker.SVGMarker([51.5, -0.09], {iconOptions: {circleText: "hello"}})
```

The README does say "All standard L.Marker options are supported." which is wrong.  The code overwrites anything passed to "icon" with the factory method passed as "iconFactory", which default to L.divIcon.svgIcon, and uses whatever options are in "iconOptions". Since you did not pass any "iconOptions", the passed icon is changed to an SVGIcon with the default options.

I originally did this because the intended use of the SVGMarker is to have a setStyle implementation compatible with SVGIcons. Allowing any icon would break this. However, I now realize that having an "iconFactory" option that takes anything is contradictory to this aim. So, I'll modify the code to allow your usage, the change is super minor, and note in the README that setStyle will break if an incompatible icon is passed.

**Comment by Joppla** [comment]
Hello,

Thanks for your reaction. I don't understand all what you wrote, but the 
given example works, that's the most important!

Met vriendelijke groet,

Jop

Op 17-03-17 om 14:45 schreef iatkin:
>
> Your issue is that you can't directly pass a custom icon to SVGMarker. 
> To customize the icon, pass a dictionary under the option 
> "iconOptions". For your example, the intended use is
>
> |var marker = new L.Marker.SVGMarker([51.5, -0.09], {iconOptions: 
> {circleText: "hello"}}) |
>
> The README does say "All standard L.Marker options are supported." 
> which is wrong. The code overwrites anything passed to "icon" with the 
> factory method passed as "iconFactory", which default to 
> L.divIcon.svgIcon, and uses whatever options are in "iconOptions". 
> Since you did not pass any "iconOptions", the passed icon is changed 
> to an SVGIcon with the default options.
>
> I originally did this because the intended use of the SVGMarker is to 
> have a setStyle implementation compatible with SVGIcons. Allowing any 
> icon would break this. However, I now realize that having an 
> "iconFactory" option that takes anything is contradictory to this aim. 
> So, I'll modify the code to allow your usage, the change is super 
> minor, and note in the README that setStyle will break if an 
> incompatible icon is passed.
>

**Comment by iatkin** [comment]
I deleted my original comment because the last part was incorrect, the change actually isn't as obvious as I thought it would be, so I won't be making it at this time. A modified version of my comment is below:

---

Your issue is that you can't directly pass a custom icon to SVGMarker.
 To customize the icon, pass a dictionary under the option
 "iconOptions". For your example, the intended use is

````js
 var marker = new L.Marker.SVGMarker([51.5, -0.09], {iconOptions:
 {circleText: "hello"}})
````

 The README does say "All standard L.Marker options are supported."
 which is wrong and has been fixed. The code overwrites anything passed to "icon" with the
 factory method passed as "iconFactory", which default to
 L.divIcon.svgIcon, and uses whatever options are in "iconOptions".
 Since you did not pass any "iconOptions", the passed icon is changed
 to an SVGIcon with the default options.

**Comment by Joppla** [comment]
Thanks!

Additional information:

In the "manual" is mentioned that only rgb-colors (fe: rgb(155,155,0) ) 
can be used but hex "#00ff00 and html-names as "red" are also possible.

Met vriendelijke groet,

Jop

Op 17-03-17 om 15:13 schreef iatkin:

**Comment by iatkin** [comment]
I originally did not allow any other formats at all but decided to allow their use as an undocumented feature since it works a little bit. If you use a color in a non-RGB format, the icon will be solid colored and you lose the ability to have individual control over the opacity of the border, fill color, circle border and circle fill color.

**Comment by Joppla** [comment]
I saw. The opacity is 100%. But why is the opacity not used by the standard svg options like  fill-opacity i.s.o. in the rgb-color?
-- 
Met vriendelijke groet,
Jop
Sent from my Android device with K-9 Mail. Please excuse my brevity.

iatkin <notifications@github.com> schreef op 17 maart 2017 16:05:30 CET:

**Comment by iatkin** [comment]
This marker was originally for a project that required the colors to be in rgb(...) format. I can make this change, but please create a new issue for this instead of putting it here.
